sudo: false
language: node_js
node_js:
  - "8"
  - "10"
branches:
  only:
    - master
before_install:
  - npm update
install:
  - npm install
  - npm install coveralls
script:
  - npm run ci
  - npm run doc
before_deploy:
  - touch dist-docs/.nojekyll
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local-dir: dist-docs
    target_branch: gh-pages
    on:
      all_branches: true
      tags: true
  - provider: npm
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
cache:
  directories:
    - node_modules

